# service node type, [DN|CN|LOG]
service-type = "LOG"
data-dir = "./mo-data"

[log]
level = "fatal"

[malloc]
check-fraction = 65536
enable-metrics = true

[observability]
disableTrace = true
disableMetric = true